name: 'Builder'
description: 'Build and push docker image'
inputs:
  credentials_json:
    description: "Credentials"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.credentials_json }}
        token_format: "access_token"

    - id: docker-login
      name: "Docker login"
      shell: bash
      run: |
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ env.IMAGE_HOST }}

    - id: build-push
      name: "Build and push"
      shell: bash
      run: |
        docker build -f ${{ env.DOCKERFILE }} -t ${{ env.IMAGE_NAME }} .
        docker tag  ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:latest
        docker tag  ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
