services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - ./deployment/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis:
    image: redis
    ports:
      - 6379:6379
  shortener:
    build:
      context: shortener
    configs:
      - config.yaml
    environment:
      CONFIG_FILE: /config.yaml
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
configs:
  config.yaml:
    file: ./deployment/configs/local.yaml