services:
  mysql:
    image: "mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - "./pkg/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
  redis:
    image: "redis:alpine"
  web:
    build: .
    environment:
      ENV: "local"
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - "~/.config/gcloud:/root/.config/gcloud"