web:
  address: ":80"
  shortHost: "localhost"
  database:
    gsmResourceID: projects/540755457828/secrets/database-config/versions/latest
  redis:
    gsmResourceID: projects/540755457828/secrets/redis-config/versions/latest
