web:
  address: ":8080"
  shortHost:
    schema: "http"
    host: "localhost:8080"
  store:
    database:
      hostname: "mysql:3306"
      database: "shortener"
      username: "root"
  cache:
    redis:
      host: "redis:6379"
