web:
  address: ":8080"
  host:
    scheme: "http"
    hostname: "localhost:8080"
  store:
    database:
      hostname: "mysql:3306"
      database: "shortener"
      username: "root"
  cache:
    redis:
      host: "redis:6379"

api:
  address: ":8080"
  database:
    gsmResourceID: projects/540755457828/secrets/database-config/versions/latest
  redis:
    gsmResourceID: projects/540755457828/secrets/redis-config/versions/latest
