web:
  address: ":80"
  host:
    scheme: "https"
    hostname: "but.la"
  store:
    datastore:
      env: DATASTORE

api:
  address: ":8080"
  database:
    gsmResourceID: projects/540755457828/secrets/database-config/versions/latest
  redis:
    gsmResourceID: projects/540755457828/secrets/redis-config/versions/latest
