name: "Docker Hub Builder"
description: "Build and push docker image"
inputs:
  dockerhub_username:
    description: "Docker Hub username"
    required: true
  dockerhub_password:
    description: "Docker Hub password"
    required: true
  dockerfile:
    description: "Dockerfile to build and push"
    required: true
  image:
    description: "Image name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.image }}:latest
          ${{ inputs.image }}:${{ github.sha }}