address: ":8080"
store:
  database:
    hostname: "mysql:3306"
    database: "shortener"
    username: "root"
  cache:
    redis:
      host: "redis:6379"
host:
  scheme: "http"
  hostname: "localhost:8080"