name: 'Deployer'
description: 'Deploy image to Cloud Run'
inputs:
  credentials_json:
    description: "Credentials"
    required: true
  env:
    description: "Environment"
    required: true
  secrets:
    description: "GSM Secrets"
    required: false

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v3

    - id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.credentials_json }}

    - id: get-config
      shell: bash
      run: echo "CONFIG=$(cat ./config/${{ env.SERVICE }}/${{ inputs.env }}.yaml)" >> $GITHUB_OUTPUT


    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        project_id: ${{ env.PROJECT_ID }}
        region: ${{ env.REGION }}
        env_vars: CONFIG=${{ steps.get-config.outputs.CONFIG }}
        secrets: ${{ inputs.secrets }}
        service: web-test
        image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
