name: Deploy

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  dh-build:
    name: Docker Hub Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build
        run: |
          docker build -f shortener/Dockerfile -t dbut2/shortener shortener

      - name: Tag and Push SHA
        run: |
          docker tag dbut2/shortener dbut2/shortener:${{ github.sha }}
          docker push dbut2/shortener:${{ github.sha }}

      - name: Tag and Push latest
        if: ${{ github.ref == 'refs/head/main' }}
        run: |
          docker tag dbut2/shortener dbut2/shortener:latest
          docker push dbut2/shortener:latest

  build-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
      - dh-build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Login to gcr
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ env.IMAGE_HOST }}

      - name: Build and Push
        run: |
          docker build -f deployment/Dockerfile -t asia.gcr.io/but-la/shortener/test --build-arg ENV=test deployment
          docker tag asia.gcr.io/but-la/shortener/test asia.gcr.io/but-la/shortener/test:${{ github.sha }}
          docker push asia.gcr.io/but-la/shortener/test:${{ github.sha }}
          docker tag asia.gcr.io/but-la/shortener/test asia.gcr.io/but-la/shortener/test:latest
          docker push asia.gcr.io/but-la/shortener/test:latest

  deploy-test:
    runs-on: ubuntu-latest
    needs:
      - build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          project_id: but-la
          region: australia-southeast1
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
          service: shortener-test
          image: asia.gcr.io/but-la/shortener/test:${{ github.sha }}

  build-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - dh-build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Login to gcr
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ env.IMAGE_HOST }}

      - name: Build and Push
        run: |
          docker build -f deployment/Dockerfile -t asia.gcr.io/but-la/shortener/dev --build-arg ENV=test deployment
          docker tag asia.gcr.io/but-la/shortener/dev asia.gcr.io/but-la/shortener/dev:${{ github.sha }}
          docker push asia.gcr.io/but-la/shortener/dev:${{ github.sha }}
          docker tag asia.gcr.io/but-la/shortener/dev asia.gcr.io/but-la/shortener/dev:latest
          docker push asia.gcr.io/but-la/shortener/dev:latest

  deploy-dev:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
      - build-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          project_id: but-la
          region: australia-southeast1
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
          service: shortener-dev
          image: asia.gcr.io/but-la/shortener/dev:${{ github.sha }}

  build-prod:
    runs-on: ubuntu-latest
    needs:
      - dh-build
      - deploy-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Login to gcr
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ env.IMAGE_HOST }}

      - name: Build and Push
        run: |
          docker build -f deployment/Dockerfile -t asia.gcr.io/but-la/shortener/prod --build-arg ENV=test deployment
          docker tag asia.gcr.io/but-la/shortener/prod asia.gcr.io/but-la/shortener/prod:${{ github.sha }}
          docker push asia.gcr.io/but-la/shortener/prod:${{ github.sha }}
          docker tag asia.gcr.io/but-la/shortener/prod asia.gcr.io/but-la/shortener/prod:latest
          docker push asia.gcr.io/but-la/shortener/prod:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - build-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gcloud Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          project_id: but-la
          region: australia-southeast1
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
          service: shortener-prod
          image: asia.gcr.io/but-la/shortener/prod:${{ github.sha }}
