name: Deploy Web
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  SERVICE: web
  DOCKERFILE: deploy/web/Dockerfile
  IMAGE_HOST: asia.gcr.io
  IMAGE_NAME: but-la/web
  PROJECT_ID: but-la
  REGION: australia-southeast1

jobs:
  dh_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dh_builder
        with:
          dockerhub_username: ${{ secrets.DH_USER }}
          dockerhub_password: ${{ secrets.DH_TOKEN }}
          dockerfile: web/Dockerfile
          image: butla/web

  build:
    runs-on: ubuntu-latest
    needs:
      dh_build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/builder
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          image_host: ${{ env.IMAGE_HOST }}
          image_name: ${{ env.IMAGE_NAME }}

  deploy-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: web-test
      url: https://web-test.but.la/
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          env: test
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
      

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: web-dev
      url: https://web-dev.but.la/
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          env: dev
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: web-prod
      url: https://web.but.la/
    needs:
      - build
      - deploy-dev

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          env: prod
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
