name: Deploy Lengthener
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  DOCKERFILE: lengthener/Dockerfile
  IMAGE_HOST: asia.gcr.io
  IMAGE_NAME: asia.gcr.io/but-la/lengthener
  PROJECT_ID: but-la
  REGION: australia-southeast1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/builder
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

  deploy-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: lengthener-test
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
  

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: lengthener-dev
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: lengthener-prod
    needs:
      - build
      - deploy-dev

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest