name: Deploy Web
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  DOCKERFILE: web.Dockerfile
  IMAGE_HOST: asia.gcr.io
  IMAGE_NAME: asia.gcr.io/but-la/web
  PROJECT_ID: but-la
  REGION: australia-southeast1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/builder

  deploy-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: web-test
      url: https://web-test.but.la/
    needs:
      - build

    steps:
      - uses: ./.github/actions/deployer
        with:
          env: test
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
      

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: web-dev
      url: https://web-dev.but.la/
    needs:
      - build

    steps:
      - uses: ./.github/actions/deployer
        with:
          env: dev
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: web-prod
      url: https://web.but.la/
    needs:
      - build
      - deploy-dev

    steps:
      - uses: ./.github/actions/deployer
        with:
          env: prod
          secrets: |
            DATABASE=database-config:latest
            DATASTORE=datastore-config:latest
            REDIS=redis-config:latest
