name: Quality
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.20

      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: shortener


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.20

      - run: go test ./...
        working-directory: shortener
