name: "Release Please"
on:
  push:
    branches:
      - '**'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go